### ISSUE TITLE
Update notification

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/Simplerenew#170]
Make it easy for users to know when there's a new version available and easy to update to it.

**Comment by htmgarcia** [comment]
Same here. 

I'm thinking as I'm using the same API details in a second site that may conflict in someway?
Just a thought

**Comment by billtomczak** [comment]
Implemented as of [v0.3.9](https://github.com/OSTraining/Simplerenew/releases/tag/v0.3.9)

**Comment by htmgarcia** [comment]
Thanks @billtomczak !
