### ISSUE TITLE
Error plus solution

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/Simplerenew#201]
Let's always try to suggest the solution when we present a problem
![alledia_-_administration_-_simple_renew__plans](https://cloud.githubusercontent.com/assets/3868028/4293138/3aa746f4-3dd3-11e4-9d7d-c3028337cf9a.png)

**Comment by billtomczak** [comment]
This issue is very old and a bit generic. We have implemented this approach when ever we catch one. Please open a new issue for any specific cases that may be found.
