### ISSUE TITLE
Third CSS theme

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/Simplerenew#220]
Make a third theme option, in addition to the current two (update).

**Comment by htmgarcia** [comment]
Added third theme https://github.com/OSTraining/Simplerenew/commit/c672694a101391af329814c53f92b8c8833b5c26 https://github.com/OSTraining/Simplerenew/commit/f62eefb6c137a4b610f67429f259048374d6aaa5

**Comment by htmgarcia** [comment]
Fixes
https://github.com/OSTraining/Simplerenew/commit/63af348f15c28230591563cd91514f557106e10f
https://github.com/OSTraining/Simplerenew/commit/5f0e743a83f75dc41f9700f1cef525d1b50ab448
https://github.com/OSTraining/Simplerenew/commit/98880a55a6a746eebf6cf39fa0e3c12fc3935a04
https://github.com/OSTraining/Simplerenew/commit/7bdb57df45704151f19cea97c1e4e38e3d409ba6

**Comment by nicksavov** [comment]
Nice job, Valentin :)
