### ISSUE TITLE
Pro feature: module to show user information

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/Simplerenew#249]
Module to display 
+ Avatar (gravatar maybe)
+ User groups associated
+ Subscription details

**Comment by billtomczak** [comment]
With the recent updates to mod_osmyaccount, it wouldn't take too much to spruce this up for public consumption.

**Comment by htmgarcia** [comment]
+1 right!

**Comment by htmgarcia** [comment]
IMO this module could be a pro version.

**Comment by billtomczak** [comment]
+1 - that's the idea!

**Comment by billtomczak** [comment]
Closing this since we have mod_osmyaccount in use/development at ostraining.com. Adding issue in that private repository.
