### ISSUE TITLE
Text hints on sign up form ... ideas for improvement.

### ISSUE THREAD

**Issue by vickythomas** [OSTraining/Simplerenew#287]
I just walked through the sign up and re-subscribe process (via SR) with the site owner.  Overall, so nice!  We did notice that this could be confusing.
The text hint if you enter a user name that is already in use is: "Enter the correct email & password for this user"   I understand the intent, but we think it possible that some OTHER person could enter a duplicate username - if so, this message is just confusing.  Can this be edited to something like:  "This username is taken.  If this was your previous username, enter the original email and password also."

**Comment by billtomczak** [comment]
Oooh! I rather like that.

**Comment by nicksavov** [comment]
+1, nice idea, Valentin! That should work well for https://github.com/OSTraining/Simplerenew/issues/292 too Very nice :)

**Comment by billtomczak** [comment]
ATTN: @vickythomas @nicksavov @htmgarcia @stevejburge 

I've implemented a system that I hope is at least a step in the right direction. Would very much appreciate feedback. Please see: http://simplerenew.ostraining.us/subscribe.

You don't ever need to submit the form, just try different user/email/password combinations and see what you think of the way I'm handling validation for those fields. Two user accounts you can use for testing:

fred / fred@ostraining.xxx
wilma / wilma@ostraining.com

passwords are the same as username.

**Comment by billtomczak** [comment]
@htmgarcia -- the styling for these new tooltip validation messages should probably be restyled.

**Comment by htmgarcia** [comment]
@billtomczak looks great! Thanks

Yes, I added a fix to make the tooltip white: https://github.com/OSTraining/Simplerenew/commit/6819086336209ba90ae9a983040d37ef88b0b8a9

**Comment by vickythomas** [comment]
Very nice!  I tried to force every 'hint'  - helpful messages.

BTW, is that (via language file or otherwise) a space within this form 
for a custom message if desired?

Vicky Thomas

------ Original Message ------

**Comment by billtomczak** [comment]
Yes, all texts are in the language file.

**Comment by vickythomas** [comment]
Really nice!

**Comment by nicksavov** [comment]
Great work, Bill! Excellent implementation :)
