### ISSUE TITLE
User Documentation for v.1.0.0

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/Simplerenew#293]

**Comment by nicksavov** [comment]
I think systematic documentation with a table of contents would be best.

Examples:

Grav:
http://learn.getgrav.org/

Akeeba Backup:
https://www.akeebabackup.com/documentation/akeeba-backup-documentation.html

**Comment by nicksavov** [comment]
https://wordpress.org/plugins/documentation/screenshots/ is the only WordPress plugin that I've found that might be worth trying.

**Comment by htmgarcia** [comment]
+1 for systematic documentation. Would be easier to search and navigate for any user

**Comment by nicksavov** [comment]
I started an outline of topics we should cover at https://docs.google.com/document/d/1L0HBlg6kf3t3MK4tzwUXNlQ5y2EYlmjaP8EVH7U90T8/edit?usp=sharing

Each bullet point is an article.

Let me know if you have any suggestions.

**Comment by billtomczak** [comment]
@nicksavov @stevejburge -- closing because I think this one is done.

**Comment by vickythomas** [comment]
Is this the location of documentation? http://simplerenew.com/installation/

**Comment by billtomczak** [comment]
Yes - everything we have is listed in the menu on the right of those pages.
