### ISSUE TITLE
Expand icon in coupon area

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/Simplerenew#294]
Clearly show you need to click to type the coupon, an icon can help:
![expand](https://cloud.githubusercontent.com/assets/4999794/5667031/1c68ac04-972a-11e4-824e-c854fd3fedef.png)

**Comment by nicksavov** [comment]
I like it, but the red's kind of bold. Most people aren't going to have a coupon and there are high rates of cart abandonment when people go searching on Google for coupons, so I'm hesitant about highlighting it.

**Comment by htmgarcia** [comment]
Actually the icon would be blue or black color. Is red in my screenshot to standout only.
I think we need an element to visually says "click here to type your coupon", not sure how accomplish this in the best way

**Comment by billtomczak** [comment]
I wonder if we only need to change the text? I like the way eventbrite handles this:
![link](https://cloud.githubusercontent.com/assets/3068131/5827816/9e1b07e2-a0b2-11e4-9ad4-eeee7b59b00a.png)

![clicked](https://cloud.githubusercontent.com/assets/3068131/5827818/a5ab50f2-a0b2-11e4-8406-f9c7e1379206.png)

**Comment by nicksavov** [comment]
+1, that's what we do for OSTraining and it seems to work well.

**Comment by htmgarcia** [comment]
+1 just change the string: https://github.com/OSTraining/Simplerenew/commit/aadc6662001f44e6436f337e314ba0e3db1b573e
