### ISSUE TITLE
Unresponsive layout

### ISSUE THREAD

**Issue by natalieyoun** [OSTraining/Simplerenew#297]
Graphics do not stack correctly in portrait layout
![image](https://cloud.githubusercontent.com/assets/10467499/5684985/010506d0-97eb-11e4-88f5-61923db57f47.jpg)

**Comment by htmgarcia** [comment]
Hi @natalieyoun 
thanks for sharing your feedback!

I already added a fix for that page. Please refresh the site.

Note: this bug is not related to Simple Renew extension.

**Comment by htmgarcia** [comment]
Thanks @billtomczak for closing this issue. I forgot to do it.
