### ISSUE TITLE
Potential checkout issue in Safari using an iPad

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/Simplerenew#298]
Safari asks if the credit card info should be saved, then after clicking No or Yes, the browser (or maybe it was the page or tab) goes in the background. It seems like a Safari bug, but maybe there's something we can do on our end.

The issue was found on Alledia.com in Safari on an iPad and it was for the OSYouTube Pro checkout.

**Comment by billtomczak** [comment]
Closing due to no recent reports
