### ISSUE TITLE
Plan Synchronization

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/Simplerenew#299]
Say what? :) What does 1 mean in this context?

![plan-sync](https://cloud.githubusercontent.com/assets/3868028/5725069/ea85f2f8-9b1d-11e4-9011-0d4060dfec58.png)

**Comment by billtomczak** [comment]
I suppose I should just remove that. There really isn't much reason for anyone to ever change this so I'm okay with hardcoding it. 

The synchronization of plans in SR with what's on Recurly needs review/rethinking anyway.
