### ISSUE TITLE
autofill duplicate fields

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/Simplerenew#303]
Take https://www.alledia.com/subscribe/ for example.

If I fill in the First Name in the basic info, it would be nice to populate it for the First Name in the billing too. Some people will have different accounts and billing names, but they can erase it.

Same goes for Last Name and Email.

**Comment by vdrover** [comment]
If there is anything we can do to push this feature up the flagpole, please let us know. It sounds simple, but it very likely would improve conversions. 

Could be something as easy as a piece of JS to populate the lower field onKeyUp once the upper field was complete.

**Comment by billtomczak** [comment]
@vdrover -- please take a look at the above commit 5ab39a7b07a183436c565098cf258739499dc2ea. Let us know if that works for you.

**Comment by vdrover** [comment]
I manually patched both these files on my test site, but there was no change in behaviour.

**Comment by billtomczak** [comment]
Make sure the js file isn't cached somewhere and that there isn't a template override in place for the template file. Please provide a  link where I can see what's going on.

**Comment by vdrover** [comment]
good call. Fix confirmed. Working as expected. And if i choose to change the biling name, my account name is unchanged.

Nice work.

**Comment by billtomczak** [comment]
Thanks! Glad it worked out. We'll push a new release with this in place soon
