### ISSUE TITLE
Add "Processing" text

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/Simplerenew#307]
[feedback from a user]
When i added the test card details, i thought it was quite slow and a while in processing. See what yo think, i know it is still test phase but if it stays the same, maybe it is a bit long. A thought, could there be something that says 'processing' when you click subscribe. 
[/feedback]

**Comment by htmgarcia** [comment]
We already have this feaure. User can apply a language override if he wants a different message.
![subscribe](https://cloud.githubusercontent.com/assets/4999794/6045472/f34390a0-ac5f-11e4-9b17-1ae9531ba179.jpg)

**Comment by htmgarcia** [comment]
@billtomczak I think replacing the check icon on the left with a loading animation would match better the purpose of this feature.

**Comment by billtomczak** [comment]
@nicksavov  -- this implies they might be using an older version. Do they have at least 0.4.0 installed? As @htmgarcia says, it looks like we implemented that change by then.


@htmgarcia  - Animations are always nice for these. Is this something that could be done entirely in css?

**Comment by htmgarcia** [comment]
@billtomczak we only need to use an icon tag with CSS classes. Font Awesome already include the animation.

**Comment by billtomczak** [comment]
Very cool.

**Comment by htmgarcia** [comment]
Here we go: https://github.com/OSTraining/Simplerenew/issues/309

**Comment by nicksavov** [comment]
You guys are right, looks like 0.2.12 is installed. But there are no updates available either in Extension Manager. He could update manually, but can we double check the updater's working?

**Comment by billtomczak** [comment]
If he's on J3.x it's possible the update site got disabled someplace along the line due to intermediate bugs in the SR deployment process. afaik the only way to re-enable is to manually reset it in the database.

Look in #__update_sites for an entry with name 'Simplerenew Updates' and make sure the enabled field is set to '1'.

**Comment by nicksavov** [comment]
Looks like http://deploy.ostraining.com/latest-release/com_simplerenew is showing 0.2.12

Adding @andergmartins

**Comment by billtomczak** [comment]
Hmm... that may be the old deploy system. Here's the current update url

https://deploy.ostraining.com/client/update/free/stable/com_simplerenew

or 
https://deploy.ostraining.com/client/update/free/stable/com_simplerenew/extension.xml
(because of j2.5 issues)

**Comment by billtomczak** [comment]
@htmgarcia -- I noticing some inconsistencies in the submit buttons. Log in as a subscriber and try using the edit account form. On submit, the button text color doesn't change. Would also be nice to implement the nice new animation you added to the subscribe/plan change forms.

The renewal form submit button is also not behaving the same as the other, but I'm not as concerned with that since we're going to change that to an ajax process sometime in the 1.0 branch.

**Comment by billtomczak** [comment]
@nicksavov -- just checked - that link you are using is from the old deploy system. The correct link is

https://deploy.ostraining.com/client/download/free/latest-stable/com_simplerenew

**Comment by nicksavov** [comment]
Ok, let's update the links and everyone else can update manually (there are only a few people using Simple Renew at the moment, so it shouldn't be an issue).

**Comment by htmgarcia** [comment]
@billtomczak you're right. 
What do I need to have the loading gray button working after user do the click?

**Comment by vickythomas** [comment]
@nicksavov Do I need to manually update my J2.5 site w/the new stable release, or let the update manager do this?  Looking at your earlier comment, not sure if it applies to me...

**Comment by billtomczak** [comment]
@vickythomas -- We just published the stable v1.0 in the last hour. It should appear automatically in the update manager for you. This is an issue for much older versions than you are using.

**Comment by billtomczak** [comment]
@htmgarcia -- All the forms in SR are designed to recognize a submit button with those two spans using the ost-text-disabled and ost-text-enabled classes.

**Comment by htmgarcia** [comment]
@billtomczak just did that: https://github.com/OSTraining/Simplerenew/issues/309

**Comment by billtomczak** [comment]
Closing this in preference to #309
