### ISSUE TITLE
Error notice when there are no more plans to subscribe

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/Simplerenew#308]
+ By being subscribed to all plans
+ Go to subscribe page

> Notice: Undefined variable: header in /components/com_simplerenew/views/subscribe/tmpl/noplans.php on line 14

**Comment by nicksavov** [comment]
https://github.com/OSTraining/Simplerenew/commit/a7687e0b3836cd693da6cb8661ac47f9867bfb17 should fix it. Needs review by Bill to make sure that's what he intended, but it appears that it is.

**Comment by billtomczak** [comment]
lol - indeed you are correct @nicksavov!

**Comment by htmgarcia** [comment]
Good catch @nicksavov , thanks!
