### ISSUE TITLE
Loading animation when buttons are disabled

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/Simplerenew#309]
For buttons that show a "processing" message, display a loading animation. This improves UX

**Comment by htmgarcia** [comment]
![loading](https://cloud.githubusercontent.com/assets/4999794/6046056/658a9272-ac64-11e4-8d8c-89e6868c0ffd.jpg)


Fixes:
https://github.com/OSTraining/Simplerenew/commit/a1108f9813e4b1e1dc9085611126c8302788eb4c
https://github.com/OSTraining/Simplerenew/commit/979a6319ade038b555dc27276ba150363c3b26da

**Comment by htmgarcia** [comment]
@billtomczak added the same spam tags in renewal page: https://github.com/OSTraining/Simplerenew/commit/d24cb397f0a2ac312cdf593c2997b2c0a4b9005a

Tested in local with no luck.

**Comment by billtomczak** [comment]
umm... yeah. Sorry. The renewal form is the one I wasn't worried about because that submit button will be going away. It doesn't load the form validation js which includes the disabling functionality.

It should work on the account editing form though :)

**Comment by htmgarcia** [comment]
Thanks for the clarification @billtomczak ,
Fix: https://github.com/OSTraining/Simplerenew/commit/9dbf2712d10b515ac8eb12027d7c35a73cc67f63

**Comment by billtomczak** [comment]
You didn't want to use the animated spinner?
