### ISSUE TITLE
Simple Renew or Simplerenew?

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/Simplerenew#314]
In many places we have this variation in the name:

a) Simple Renew
b) Simplerenew

I think a) is the right one. Thoughts?

**Comment by stevejburge** [comment]
Yes, a) unless needed for code purposes

**Comment by nicksavov** [comment]
+1

**Comment by htmgarcia** [comment]
Fixed: https://github.com/OSTraining/Simplerenew/commit/ef94c6ffef1f69eb1dbf95eb640ea1ac3ea908c6
