### ISSUE TITLE
Simple Renew icon

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/Simplerenew#317]
![logo](https://cloud.githubusercontent.com/assets/4999794/6360189/ca8b5e66-bc3d-11e4-9e67-71fcc42a6593.jpg)

**Comment by htmgarcia** [comment]
@billtomczak added the CSS however is not loaded in backend.

**Comment by billtomczak** [comment]
@htmgarcia -- thank you! admin UI was not always loading the css.

**Comment by htmgarcia** [comment]
Thanks @billtomczak !

**Comment by billtomczak** [comment]
@htmgarcia -- looks like maybe the wrong image to be using?

![admin](https://cloud.githubusercontent.com/assets/3068131/8609765/6bacdc0e-265e-11e5-887e-38f34aba6296.png)

**Comment by htmgarcia** [comment]
@billtomczak I did a new update to make the logo smaller: https://github.com/OSTraining/Simplerenew/commit/b59f2eeca0462cf3dcfe120851df396961ce53de

**Comment by htmgarcia** [comment]
Now I think, maybe is better to use a white logo instead.

**Comment by nicksavov** [comment]
The white looks good
