### ISSUE TITLE
Global option for "Allow Coupon"

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/Simplerenew#318]
"Allow Coupon" needs a global option for its default when creating a new subscribe menu item

**Comment by billtomczak** [comment]
:) you read my mind. This came up for me during the launch on ostraining.com

**Comment by billtomczak** [comment]
@stevejburge @nicksavov Please review.

* I've added a global default in the configuration screen:
![couponallow](https://cloud.githubusercontent.com/assets/3068131/6495731/a653e23a-c281-11e4-966f-64f2fd096821.png)

* and the default for new subscription menus is to use the global setting:
![couponmenu](https://cloud.githubusercontent.com/assets/3068131/6495736/b958eea2-c281-11e4-8ea5-c3ab4ce7a481.png)

**Comment by nicksavov** [comment]
Looks good, Bill!

**Comment by billtomczak** [comment]
okay - feature merged to v1.0.x and v1.1.x
