### ISSUE TITLE
Add user group as class in the plans

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/Simplerenew#322]
The idea is to automate a custom CSS class to define a background color.

https://github.com/OSTraining/Simplerenew/blob/master/src/site/views/subscribe/tmpl/default_plans.php#L34

Example of html generated for a listed plan in subscribe:

```<span class="simplerenew-plan plan_code_plan-alias user-group-user-group-alias">```

Where user-group-user-group-alias means the user group (adding an hyphen to remove spaces).

**Comment by stevejburge** [comment]
Great idea

**Comment by billtomczak** [comment]
Since there is no formal alias for groups, only a title, I would push for using the group ID instead. All it would take to break formatting would be to change a group title from 'Video Member' to 'Video Members' -- for example. IDs never change.

**Comment by htmgarcia** [comment]
+1

**Comment by billtomczak** [comment]
@htmgarcia -- note that I did change the plan classes to use dashes instead of underscores. I don't think this will affect the SR css. But changes in this commit will affect ostraining.com

**Comment by htmgarcia** [comment]
This update should take care of that: https://github.com/OSTraining/tpl_ostraining_lava/commit/aa982914e916fbeda80d4906de02151669f1beba

**Comment by htmgarcia** [comment]
Thanks @billtomczak !

**Comment by htmgarcia** [comment]
I noticed the UG id classes are not added for OSTraining. I guess this fix will be available in the next release.

I'll keep this issue open in the meanwhile.
