### ISSUE TITLE
Failed Payment Notices

### ISSUE THREAD

**Issue by billtomczak** [OSTraining/Simplerenew#324]
Verify what happens in the case of a failed payment.

Currently no action taken on Failed Payment notice. This should result in the user being reset to a non-subscriber user group.

**Comment by billtomczak** [comment]
Recurly does the dunning management. If a payment fails, the user can continue to be an active subscriber based on the schedule set there. Simple Renew should only watch for subscription expiration and not pay any attention to payments.

**Comment by nicksavov** [comment]
+1
