### ISSUE TITLE
Improve design for plans list

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/Simplerenew#325]
Desired result:
![7-day-trial](https://cloud.githubusercontent.com/assets/4999794/6534717/3644436a-c405-11e4-9bdd-f029b9014f51.png)

**Comment by htmgarcia** [comment]
This improvement require change the method name() https://github.com/OSTraining/Simplerenew/blob/v1.0-dev/src/admin/library/html/plan.php#L28

@billtomczak thoughts?

**Comment by OSTraining** [comment]
You can't change the method. This would break b/c.

I don't see why the method needs to be changed anyway. You've changed the call and those arguments are optional.

**Comment by htmgarcia** [comment]
I need to wrap the trial information in a separate span tag. As I notice this would be complex, I suggest add the wrapper in the method. If this solution is not appropriate, I'm afraid we can't add it.

Currently the html for the plan is generated as follow:

```<span class="simplerenew-plan">
    <input type="radio" data-description="" value="" id="" name="planCodes" data-recurly="plan">
    Plan name $00.00 00 Months - 7 Day Trial
</span>```

With my update, would be:

```<span class="simplerenew-plan">
    <input type="radio" data-description="" value="" id="" name="planCodes" data-recurly="plan">
    Plan name $00.00 00 Months 
    <span class="simplerenew-plan-trial">00 Day Trial</span> 
</span>```

Commit: https://github.com/OSTraining/Simplerenew/commit/dc34854790aff87fb0b7d40d8f3476a336f94cb9

**Comment by billtomczak** [comment]
I must not be getting something here. I don't understand why this wouldn't work?

```
<span class="<?php echo 'simplerenew-plan user-group-' . $plan->group_id; ?>">
   <.. stuff omitted>
   <?php
   echo JHtml::_(
      'plan.name',
      $plan->name,
      $plan->currency,
      $plan->amount,
      $plan->length,
      $plan->unit,
   );
   ?>
   <span class="simplerenew-plan-trial">
      <?php echo JHtml::_('plan.trial', $plan->trial_length, $plan->trial_unit); ?>
   </span>
</span>
```

**Comment by htmgarcia** [comment]
We only need the span tag

```<span class="simplerenew-plan-trial"></span>```

when the plan include trial period. I can add an if to validate that in the view but that means repeat code every time since the validation is already done in the name() method.

**Comment by nicksavov** [comment]
I think it should go directly into https://github.com/OSTraining/Simplerenew/blob/v1.0-dev/src/admin/library/html/plan.php#L49 . I don't think it will break anything for the current sites that are out there.

**Comment by nicksavov** [comment]
I think it's an improvement that they'll like.

**Comment by billtomczak** [comment]
Okay, I forgot about the if statements, but my initial confusion stands. If you simply don't pass those two arguments to plan.name you get exactly what you want and there is no need to change the method at all.

Sorry! I'm really not getting the problem here

**Comment by htmgarcia** [comment]
Sorry if I wasn't enough clear. We only need add a span tag to wrap the trial period in order to add some CSS to stand out. 
Please take a look to my previous comment https://github.com/OSTraining/Simplerenew/issues/325#issuecomment-79327967

Here is a desired result (the orange background):
![trial](https://cloud.githubusercontent.com/assets/4999794/6646570/e85923c8-c98b-11e4-897b-ec2c9f195e9f.jpg)

**Comment by nicksavov** [comment]
@billtomczak , I think that makes sense. So for:
https://github.com/OSTraining/Simplerenew/commit/e815d5bc6c787237f9ced64b7b2a421971d390ee

Keep everything the same, except for don't change anything in src/admin/library/html/plan.php , correct?

**Comment by htmgarcia** [comment]
@nicksavov that was the firts proposal, the new one is simpler (like in my previous screenshot)

**Comment by nicksavov** [comment]
I like the first one a lot better. Your first one is awesome :)

**Comment by billtomczak** [comment]
@nick - re: your comment on e815d5b - that is correct

**Comment by billtomczak** [comment]
Perhaps the case for b/c is not very strong, and perhaps at this early a stage in the game it is a more philosophical argument. It's doesn't make it any less important to attend to the issue.

In other words, I don't see a good enough reason to change the method. 

1. You can do what you want in the template with the api as is.
1. The method can no longer display all relevant plan info as a single string. We may find ourselves regretting losing that someday.
1. There is an inconsistency in having plan.name return a plain string with an embedded html wrapper

If you want to do something simpler and elegant in the template file, I would suggest creating a new method to consistently produce exactly what you want. Perhaps something like plan.html or plan.display. Then you don't have to do anything in the template file at all. We don't break b/c and we still have the functionality of the original methods.

If at some point we decide those methods are no longer useful and we really don't want them anymore, we can mark them as deprecated and remove in a later release.

**Comment by billtomczak** [comment]
and btw - if you create a new special purpose method that suits your needs. The next time you want to change the plan display everywhere (keep in mind srgroupleaders is also displaying plans like this), you won't have to change any template files at all. just your new method.

**Comment by htmgarcia** [comment]
Based on @nicksavov suggestions (https://github.com/OSTraining/Simplerenew/commit/e815d5bc6c787237f9ced64b7b2a421971d390ee) I made a new try: https://github.com/OSTraining/Simplerenew/commit/89f985239d4ffa21929a5c370ad99a54e8c70e06

**Comment by htmgarcia** [comment]
Remaining issue in smaller screens:
![break](https://cloud.githubusercontent.com/assets/4999794/6695819/cac3ca2c-cca9-11e4-8e3b-0953e642be85.jpg)
