### ISSUE TITLE
User feedback shows they don't understand 'email in use' message

### ISSUE THREAD

**Issue by vickythomas** [OSTraining/Simplerenew#326]
Hi, as you know, we asked our users to move from the old sub system to the new one, the new on being via Simple Renew.  Their link: https://dnc.dressagenaturally.net/dnc-change-2015
Many have had problems and frustrations.  Their comments highlight that although it makes sense to me, they are not seeing the helpful hints re: 'email in use'. They just notice that the 'subscribe' button doesn't work, and that it 'doesn't like' the email address.  So, maybe rethink how you provide that info?  Also, I need to put another message just above the subscribe button to tell them AGAIN what to do re: "email in use" as many obviously are not clicking on the "?" or don't understand what it means.  Do you have empty language fields set up for the form, that I can add this via the language manager?  For now, I might add text in a module just below the form.  Thanks, Vicky

Here are some of the comments collected:

I have tried it and it won't let me go to Paypal. The link for Paypal won't allow me to click 

now it wont do anything when I click subscribe? when trying to go via paypal

I'm writing again to get help with this.  It says User Name in use and will not let me subscribe.  I
can't get rid of the email in use warning!

I have tried to set up my new regulations but even when I put my password in it says the user name is in use.

I am trying to complete this and filled in all the fields, but the subscribe button doesn't work... I pushed it several times, but nothing happens....

Trying to upgrade, the computer keeps telling me that my emailadress is in use. I ignore that, but the computer doesn't and wont move on. I cant subscribe. Help!

Having loads of trouble with the on line form, it won't let me push the subscribe button on the credit card option and I get an "endless spin" for the PayPal (screen shot attached).

I was filling in the new plan info as requested but it won't let me go to Paypal

I'm still not getting anything when I click on the PayPal button. 

Tried again and after pressing paypal then subscribe it just highlights back to the email address and I pressed subscribe again and it just repeats the above. 

I have attempted to complete the new subscription though the system is not happy about me using the same email address and hence will not proceed with the subscription.

I tried to put in the new information for the changeover last night and it would not let me subscribe. I continued on and filled everything in but it would not let the subscribe link be clickable to go to Paypal or use a credit card.

**Comment by nicksavov** [comment]
Hi Vicky!

Sorry to hear about that! Have you tried making the form only accessible to logged in users? That way, when they click the link, they'll have to log in first, then be redirected to sign up (without needing username, email, or password).

**Comment by vickythomas** [comment]
Sounds helpful.  Please confirm the best way to make this happen - make the menu item to that link 'registered'?

**Comment by nicksavov** [comment]
Yes, but please test and double check to be sure. Sometimes there are login redirects on a site that redirect all logged in users to a dashboard.

**Comment by vickythomas** [comment]
I suspect that might happen.  Thanks.  I put a lot of text on the page w the form asking them to use the same username, etc.

**Comment by vickythomas** [comment]
Update ... I added this as an issue, as (surprising to me) the current way of explaining what to do if using an 'email in use' ... is not intuitive to more users than expected.  Please think about an improvement here.
Also, I wonder if anything in the form can be edited or added via the language file?  This could be useful in some circumstances, even if temporary.   
I appreciate that Nick provided some technical advice but please note the suggested improvements.  BTW, I think you all are amazing!

**Comment by billtomczak** [comment]
@vickythomas, @nicksavov -- where do things stand on this one?

@vickythomas, we did include the ability to insert modules in the subscription pages. Maybe you could play with that a bit with a custom html module? The positions are:

simplerenew_plans_top
simplerenew_plans_bottom
simplerenew_submit_top
simplerenew_submit_bottom

Just a thought.

**Comment by nicksavov** [comment]
I think Vicky is right. Many users aren't used to tooltips so they don't pick up the hints. I think what we'd have to do is go back to the "Display a login" box idea. If the username or email is taken, offer them a login box.

**Comment by billtomczak** [comment]
Makes sense - will be a bit of work so won't happen too immediately.

**Comment by nicksavov** [comment]
Hi Vicky,

This one should be fixed for our next release of Simple Renew. You can see the implementation at https://www.ostraining.com/free-trial-video/

Bill did a great job with it.

If you have any issues, please open up a new issue report. Thanks!

Closing this one for now.

**Comment by vickythomas** [comment]
Hi Nick!
It's been a while since we talked.  I see you guys ever improving SimpleRenew.
My clients are ALMOST ready to ditch AEC, and that will be a very happy day for me ... thanks in large part to SimpleRenew. 
Thank you for creating this extension for subscriptions!
I looked at that link, but couldn't get it to think I was using an existing email.  I can test it better when I update our site w/the new release.
Best, Vicky

**Comment by vickythomas** [comment]
Hi Nick, I just updated to v 1.16.  I don't see a difference in how 'email in use' is communicated.  Also, I just saw (again) the note re: module positions; is that in the documentation yet?  It is such a great feature - let them know!

**Comment by vickythomas** [comment]
... is it the "Already Have an Account Button?" ... nice!

**Comment by nicksavov** [comment]
Thanks for kind words, Vicky!

As to v1.1.16, make sure you're logged out and go to https://dnc.dressagenaturally.net/dnc-change-2015 . You'll see a blue "Already Have an Account?" button.

We took down the simplerenew.com and moved the documentation to https://www.alledia.com/docs/simplerenew/ (our sister site). That being said, it doesn't look like the module position docs are in there yet. But, you can use ?tp=1 behind the URL to see the module positions. Just be sure to enable viewing the module positions within template manager's options.

**Comment by vickythomas** [comment]
Yes, I saw the button a few seconds after I wrote the original note :-\

Documenation is everything, so brag about all the great options available.  If you ever want me to review your documentation and provide comments, will happily donate the time for that.

**Comment by nicksavov** [comment]
lol, great on the button! I think for users it will be more obvious when they are filling out the form, rather than skimming looking for a difference. So hopefully it should work out really well.

Wonderful, thanks Vicky!

Yes, we have a detailed change log at https://github.com/OSTraining/Simplerenew/releases

One of the big things we've been working on that's still in beta is SRSubs. That's what we created for manual subscriptions that don't have billing info (and thus can't go in Recurly). We're using it at OSTraining already.
