### ISSUE TITLE
High priority: Paypal doesn't work when logged in

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/Simplerenew#328]

**Comment by vickythomas** [comment]
any progress?

**Comment by nicksavov** [comment]
Hi Vicky,

It's a known issue for Recurly's Paypal implementation due to the way modern browsers treat popups, unfortunately. It has to do with the browser blocking popups because it thinks its not generated by a user request (the submit on the form). There should be a notification displayed by the browser asking you to accept or deny the popup.

That being said, we plan to find a workaround, even if it means rewriting a lot of the code. We worked on it most of today and Bill's going to continue on Monday until it's fixed. Sorry that I don't have better news for you, but we won't give up on this one, so expect a fix early next week sometime.

**Comment by vickythomas** [comment]
Hi Nick, thanks for the update. my browser does allow pop ups, & I did not
see any notification otherwise. Maybe that's helpful info.

**Comment by nicksavov** [comment]
Hi Vicky,

Bill fixed it :) V1.1.1 should have the fix:
https://github.com/OSTraining/Simplerenew/releases/tag/v1.1.1

**Comment by vickythomas** [comment]
Hi Nick, thanks.  I will install and test it first thing in the morning. 
  Thank you!!
Vicky Thomas
Owner, RF Web Design
Ph: 910-556-9088
Email: support@rfwebdesign.com



------ Original Message ------

**Comment by vickythomas** [comment]
I updated SR and tested it:
 In both Chrome and Firefox, I saw a message that pop-ups were blocked and then selected the option to allow pop-ups.  I didn't see that message before ... maybe I wasn't looking for it?  In Chrome, when I 'allowed popups from this site', that opened a new tab with paypal payment page (thank you, Chrome!).  
In FF, no.  If FF, I had to (after allowing popups from that site) refresh the 'join' page, then again select PayPal and 'subscribe'.  
IE asked quite clearly if I wanted to allow popups for that site, and when I indicated 'yes' IE refreshed the subscribe page ... once I figured that out, I had to again select paypal and 'subscribe', after which it opened a new tab w paypal payment page. 
In Safari for Windows 7, no message of popups blocked and no completion ... just the spinning wheel and message 'your sub is being processed' SR message.  So, I would say this is not working on Safari, at least not here.
I can't test Safari on a Mac.

**Comment by billtomczak** [comment]
thanks @vickythomas! Very helpful.

At least we're seeing improvement! I have some ideas for getting this even cleaner but the popup issue may never go away entirely. Different browsers have different rules and the need to provide a secure PCI-compliant checkout creates some interesting......*challenges*

Thanks for your patience and working with us on this.

**Comment by vickythomas** [comment]
@billtomczak  Yes, it's better!  I also added this comment  to joomla users who will subscribe (hope they see it): 
"PayPal users, you may need to 'allow popups' for 'web site url' in order to display the paypal payment page. We've found that the Chrome web browser works best for the subscribe process."  Anything to help them get through the process with minimal frustration .... :-)

**Comment by billtomczak** [comment]
Yes - agree. I was thinking that we should make a message like that a standard part of the paypal tab.

Did you customize the language string to do that?

**Comment by vickythomas** [comment]
No, I never did figure out which were language strings ... I just added that text to a module.  Is there a guide as to what parts of this form are editable?  If no guide, can you explain which are language strings? Thanks.

**Comment by billtomczak** [comment]
Do you know about creating language overrides in Joomla? I seem to recall you've done that before. All text in SR pages are either in language strings you can override or come directly from Recurly. A search for paypal as a value at ostraining.com turned up five results. All Simple Renew string constants begin with COM_SIMPLERENEW.

Meantime, we're adding a new language string specifically for the popup warning.

See a8bd68b5312eeeed049546486a26234722aeff39

@nicksavov, @htmgarcia -- please review this commit and make any changes you deem helpful.

**Comment by billtomczak** [comment]
@vickythomas, here's the end result of that change:

![popupwarn](https://cloud.githubusercontent.com/assets/3068131/6736754/072ff3ca-ce24-11e4-8593-944081604e68.png)

**Comment by vickythomas** [comment]
Well, isn't that clever!  What a nice design @billtomczak !  Yes, I do know about language overrides, but I did not realize that all text in SR pages that are not from recurly could be overrridden in language overides.  
You should toot your horn about that in the documentation: http://simplerenew.com/customizing-text/

**Comment by nicksavov** [comment]
@billtomczak looks great, expect for the 'web site url' part. Was there a reason that was used?

Also, need to capitalize Paypal.

How about:
"After clicking Subscribe, you may need to 'allow popups' in order to display the Paypal payment page"

**Comment by vickythomas** [comment]
I ended up with this:  
Click the "Subscribe" button to go to PayPal.com.<br /><br />Then, if nothing happens for several seconds, you may need to  'allow popups' for '(website url placed here)' in order to display the PayPal payment page.

**Comment by billtomczak** [comment]
@nicksavov - I put almost no thought into this at all :)

I copied @vickythomas's  text from her original comment above. I leave it to you guys with superior human communication skills to make whatever adjustments you like. Remember to make changes in the [v1.1-dev branch](https://github.com/OSTraining/Simplerenew/tree/v1.1-dev).

**Comment by nicksavov** [comment]
Thanks Vicky!

OK, all set:
https://github.com/OSTraining/Simplerenew/commit/f57e2695a3ac22257745b22b9fd48be256bb4c25

I removed "(website url placed here)", since it would require a language override by every site to use it and I think it's fine without the URL.

Let me know if it needs tweaking.

**Comment by vickythomas** [comment]
That makes good sense to me!  Then, anyone can edit based on their needs. So many of my users will see the message "allow popups for 'url' " ...  that I wanted to add that detail. Thanks.

**Comment by nicksavov** [comment]
+1 :)

**Comment by htmgarcia** [comment]
@billtomczak added a small touch: https://github.com/OSTraining/Simplerenew/commit/a9b86fa52807ec8ff946fb842fdac62a698303e0

**Comment by billtomczak** [comment]
@vickythomas @nicksavov -- since my reworking of the code in 06c02dfcc6f90b0e6e7fe00f48eca089c3fd45ca seems to have addressed the popup issue, I am closing this issue. If the popup problem in some other form appears again, please start a new issue.

Thanks both of your for your stellar help in dealing with this epically annoying problem!!

**Comment by billtomczak** [comment]
btw - it will be officially released in the next release due on Monday 3/31.
