### ISSUE TITLE
Organize plans list

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/Simplerenew#329]
![listing-plans](https://cloud.githubusercontent.com/assets/4999794/6690196/a509a1b4-cc84-11e4-83a5-85ad7ced0e3c.png)

**Comment by htmgarcia** [comment]
@billtomczak added in a separate branch due require your approval please, specially for https://github.com/OSTraining/Simplerenew/commit/7218d06967241bb88e774572ae2f0864a47e74b1#diff-8924d72130b3f43d69e8c82c9acf761a

**Comment by nicksavov** [comment]
Hey Valentin,

I love your design at https://github.com/OSTraining/Simplerenew/issues/325 and I think it's near perfect. I think we should stay with it.

**Comment by htmgarcia** [comment]
Hey Nick,
actually is the same design. This new improvement split the plan name + plan lenght/price to keep visually more organized. The plans are using the same width + trial label if exist

**Comment by nicksavov** [comment]
Yeah, I don't like it :D It's too big and bulky. The other one is compact, to the point, and stylish.

Just my 2 cents :)

**Comment by billtomczak** [comment]
@htmgarcia -- please see recent commit.

I know I'm being annoying and finicky here, but I really want to make sure we can be as clear as possible on the purpose of packages of code. I know I not particularly clear on this in many cases myself. I've found the JHtml methods especially annoying in this regard.

I'd really like to maintain the simplicity of JHtmlPlan. It currently generates basic formatted text with no html. So I've created a couple new methods in JHtmlSr for displaying the plan info wrapped in html. I'm hoping this will make both of us happy. It simplifies the template and providers easier standardization across addons - I have slightly different display needs for plans in SRGroupLeaders and this arrangement should make it easier to track changes you want to make. That's the hope at any rate.

Also, I did a full install from this branch to ghostexplained just to be sure, but the plan display is a bit messed up in Firefox Windows:

![plans](https://cloud.githubusercontent.com/assets/3068131/6839387/d02ff446-d324-11e4-8b18-3e11d7d0217b.png)

I agree with @nicksavov -- I really liked your original design, this one feels heavy to me.

**Comment by htmgarcia** [comment]
I'm easy, I'm ok with any of both versions.

@stevejburge thoughts?

**Comment by nicksavov** [comment]
Looks like this is holding up some other issues (e.g. https://github.com/OSTraining/Simplerenew/issues/336). Let's go ahead and close it, based on the 2-1 vote :P  ... I really like your original design, Valentin :)
