### ISSUE TITLE
High Priority:  Error on Sign Up Form "Billing State/Province Required"

### ISSUE THREAD

**Issue by vickythomas** [OSTraining/Simplerenew#332]
Subscribers are getting this error, even though they have entered the state.  I confirmed this error.  My client said this started today ... I updated SR to v.1.1.2 last night ...  
Please fix ASAP.  Or, if I need to roll back for quick fix ... any idea which version to roll back to?

![simplerenewerror-20mar2015](https://cloud.githubusercontent.com/assets/8184561/6752677/db1a073a-cee6-11e4-8f1b-78fca381af5b.png)

![simplerenew-20mar2015](https://cloud.githubusercontent.com/assets/8184561/6752678/dced468a-cee6-11e4-9aed-a2f070d48cbe.png)

**Comment by billtomczak** [comment]
Confirmed the problem - working on it - should have a patch out within the hour.

**Comment by nicksavov** [comment]
Thanks Bill!

**Comment by billtomczak** [comment]
@vickythomas -- building the hot fix now

**Comment by billtomczak** [comment]
@vickythomas -- please confirm if 1.1.3 fixed the issue

**Comment by vickythomas** [comment]
@billtomczak  yes - thank you!

**Comment by billtomczak** [comment]
Woo hoo!! Sorry for the scare!

**Comment by vickythomas** [comment]
Thanks for the quick fix.  The web site owner is actively asking it's subscribers to re-sub via recurly.  Fortunately, he took the time to send a note this morning:
"We are having an issue today - several people have emailed and they are getting an error when trying to subscribe - wondering if you have any ideas why this is coming up all of a sudden - we haven't had any mention of this before" and then provided a note from his client explaining her experience w/this.
Best, Vicky

**Comment by billtomczak** [comment]
It's always especially nice to get enough information to have a prayer of identifying the problem.

**Comment by vickythomas** [comment]
Yes, it is :-)

------ Original Message ------
From: "Bill Tomczak" <notifications@github.com>
