### ISSUE TITLE
"Set up" cost not displayed

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/Simplerenew#336]
See:
https://secure.helpscout.net/conversation/81730385/12023/

**Comment by billtomczak** [comment]
Got it. Yes - not something we've used much. This should be fairly straightforward to add.

**Comment by htmgarcia** [comment]
Bingo! We forgot to display in somewhere:
```
<?php echo $plan->setup_cost; ?>
```

My first thought is include $plan->setup_cost in the name method if possible: https://github.com/OSTraining/Simplerenew/blob/v1.1-dev/src/admin/library/html/plan.php#L28

**Comment by htmgarcia** [comment]
Of course, I need to validate if the setup value exist (different to zero).

**Comment by billtomczak** [comment]
We'll need to get closure on the [Improve-plans-list-design](https://github.com/OSTraining/Simplerenew/tree/Improve-plans-list-design) branch first. The way plans are being displayed changes drastically in that branch.

See https://github.com/OSTraining/Simplerenew/blob/Improve-plans-list-design/src/admin/library/html/sr.php#L234

**Comment by htmgarcia** [comment]
Sounds fair. Let me know then, please.

**Comment by billtomczak** [comment]
I'm sorry, I thought we were waiting for feedback from @stevejburge on #329?

**Comment by htmgarcia** [comment]
You're right @billtomczak, is important to get feedback on that update before doing more changes.

**Comment by htmgarcia** [comment]
I think we can continue working this update. 

@billtomczak in which branch should I work?
a. https://github.com/OSTraining/Simplerenew/tree/v1.1-dev
b. https://github.com/OSTraining/Simplerenew/tree/development

**Comment by billtomczak** [comment]
@htmgarcia -- Please use the [development branch](https://github.com/OSTraining/Simplerenew/tree/development). I've removed the v1.1-dev branch.

**Comment by billtomczak** [comment]
Looks like 24f6f3bde2a988cee248e9796dbdd95d1c8f8854 took care of this.
