### ISSUE TITLE
Notification of switching to a new plan

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/Simplerenew#337]
Todo: In the account area, we need to make it clear for users if their account will be switched to a new plan at the next renewal, as well as the date of the switch.

**Comment by billtomczak** [comment]
I take it this means what we have isn't clear enough?

![pending](https://cloud.githubusercontent.com/assets/3068131/7074617/bc6a97a8-deb0-11e4-8f71-d4898ee4046f.png)

**Comment by nicksavov** [comment]
I guess they missed it somehow. Let's close and see if it comes up again.
