### ISSUE TITLE
If you're in a free trial, Recurly says "You don't have a membership"

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/Simplerenew#339]
![screen shot 2015-04-07 at 9 29 39 am](https://cloud.githubusercontent.com/assets/3868028/7024152/bc0eb310-dd08-11e4-9e3e-6cd4b2539439.png)

**Comment by billtomczak** [comment]
Fixed by converting mod_osmyaccount to use Simple Renew: [OS MyAccount v1.2.0](https://github.com/OSTraining/mod_osmyaccount/releases/tag/v1.2.0)
