### ISSUE TITLE
TLS Checking?

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/Simplerenew#347]
Should/can we do more specific checking at https://github.com/OSTraining/Simplerenew/blob/master/src/admin/library/joomla/view/site.php#L92 for TLS?

Reference:
https://blog.recurly.com/pci-dss-3.1-standard-released-with-immediate-effect

**Comment by billtomczak** [comment]
All that does is make sure the page is using https. I would consider it the responsibility of the host to make sure they are using the appropriate standard. This would be an issue if we were opening a socket stream that required secure communications.

**Comment by nicksavov** [comment]
Great, sounds good!
