### ISSUE TITLE
Extra spacing after subscription plan in subscribe form

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/Simplerenew#348]
https://github.com/OSTraining/Simplerenew/blob/master/src/site/views/subscribe/tmpl/default_mplans.php#L88
https://github.com/OSTraining/Simplerenew/blob/master/src/site/views/subscribe/tmpl/default_plans.php#L86

are generating extra spacing when they are blank, due to:
https://github.com/OSTraining/Simplerenew/blob/master/src/media/css/themes/default.css#L365

Could we somehow add the HTML markup only if there's an error message?

**Comment by billtomczak** [comment]
The html is used in js to indicate where error messages can be displayed so it has to be there. I would suggest adding/removing a css class on error generation. I'd have to look into the jquery validation code, but that should be possible.

**Comment by nicksavov** [comment]
Good idea!

**Comment by htmgarcia** [comment]
I did some tweaks for a proposal that would be applied only in the main plans in OSTraining, this is the end result: https://www.ghostexplained.com/video-monthly/

I overrided the margin to 10px here: https://github.com/OSTraining/Simplerenew/blob/master/src/media/css/themes/default.css#L365

I think is not necessary to apply any change in SR. We can survive with CSS overrides.

**Comment by billtomczak** [comment]
@nicksavov -- does that sound okay? Leave things as they are and reopen this (or create a new issue) if someone besides us brings it up?

**Comment by nicksavov** [comment]
Yes, that sounds good. Thanks guys!
