### ISSUE TITLE
Is the Paypal popup warning still needed?

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/Simplerenew#349]
Is COM_SIMPLERENEW_POPUP_PAYPAL_WARN still needed after the recent optimization by @billtomczak ? We haven't had any reported issues after the optimization.

**Comment by OSTraining** [comment]
I'd like to remove it. Is graphically clunky

**Comment by htmgarcia** [comment]
+1

**Comment by billtomczak** [comment]
Just a teeny bit scary because of the possibility of leaving some user hung up someplace. But I agree

**Comment by htmgarcia** [comment]
@billtomczak  should we leave a param to enable/disable from admin > options just in case?

**Comment by billtomczak** [comment]
That seems like a reasonable approach to me. An advanced option that defaults to it not showing?

**Comment by htmgarcia** [comment]
Perfect!
Thank you @billtomczak !
