### ISSUE TITLE
Show discounted price in plan button

### ISSUE THREAD

**Issue by billtomczak** [OSTraining/Simplerenew#350]
![coupons](https://cloud.githubusercontent.com/assets/3068131/7841941/d893f3ba-0454-11e5-8f25-6c4a82c40ed5.png)

When a coupon is selected, display discounted price in the plan buttons to which it applies.

**Comment by htmgarcia** [comment]
+1

**Comment by htmgarcia** [comment]
Let's track this issue from #377
