### ISSUE TITLE
Incorrect Joomla Permissions on Subscription?

### ISSUE THREAD

**Issue by ActiveOrganisation** [OSTraining/Simplerenew#351]
QUESTION

Hiya... 

When the User subscribes with Simple Renew, the page refreshes and the user then seems to have access. However, it appears that the JUser Object is not quite right. On Subscription, it looks like this:

JUser Object
(
    [isRoot:protected] => 
    [id] => 597
    [name] => Adam Clark
    [username] => AdamClark
    [email] => active_computing@hotmail.com
    [password] => $2y$10$Lu.g1YeFtXs8/qWFegoIM.qgno1cGgARnwKmEoWHbKubUSr2a9lu.
    [password_clear] => 
    [block] => 
    [sendEmail] => 0
    [registerDate] => 2015-06-08 07:36:37
    [lastvisitDate] => 2015-06-08 07:36:46
    [activation] => 
    [params] => {}
    [groups] => Array
        (
            [0] => 10
        )

    [guest] => 0
    [lastResetTime] => 0000-00-00 00:00:00
    [resetCount] => 0
    [requireReset] => 0
    [_params:protected] => Joomla\Registry\Registry Object
        (
            [data:protected] => stdClass Object
                (
                )

            [separator] => .
        )

    [_authGroups:protected] => Array
        (
            [0] => 1
            [1] => 2
            [2] => 10
        )

    [_authLevels:protected] => Array
        (
            [0] => 1
            [1] => 1
            [2] => 2
        )

    [_authActions:protected] => 
    [_errorMsg:protected] => 
    [userHelper:protected] => JUserWrapperHelper Object
        (
        )

    [_errors:protected] => Array
        (
        )

    [otpKey] => 
    [otep] => 
    [socialConnectData] => stdClass Object
        (
            [image] => //www.gravatar.com/avatar/82543e39dcc532109d25e5d2ea5838f3?s=80&d=https%3A%2F%2Fwww.snipsquirrel.com%2Fmedia%2Fsocialconnect%2Fimages%2Favatar.jpg
            [type] => 
        )

)

And.... when the user logs out and logs back in again, it looks like this: 

JUser Object
(
    [isRoot:protected] => 
    [id] => 597
    [name] => Adam Clark
    [username] => AdamClark
    [email] => active_computing@hotmail.com
    [password] => $2y$10$Lu.g1YeFtXs8/qWFegoIM.qgno1cGgARnwKmEoWHbKubUSr2a9lu.
    [password_clear] => 
    [block] => 0
    [sendEmail] => 0
    [registerDate] => 2015-06-08 07:36:37
    [lastvisitDate] => 2015-06-08 07:43:44
    [activation] => 
    [params] => {}
    [groups] => Array
        (
            [10] => 10
        )

    [guest] => 0
    [lastResetTime] => 0000-00-00 00:00:00
    [resetCount] => 0
    [requireReset] => 0
    [_params:protected] => Joomla\Registry\Registry Object
        (
            [data:protected] => stdClass Object
                (
                )

            [separator] => .
        )

    [_authGroups:protected] => Array
        (
            [0] => 1
            [1] => 2
            [2] => 10
        )

    [_authLevels:protected] => Array
        (
            [0] => 1
            [1] => 1
            [2] => 2
            [3] => 7
        )

    [_authActions:protected] => 
    [_errorMsg:protected] => 
    [userHelper:protected] => JUserWrapperHelper Object
        (
        )

    [_errors:protected] => Array
        (
        )

    [aid] => 0
    [otpKey] => 
    [otep] => 
    [socialConnectData] => stdClass Object
        (
            [image] => //www.gravatar.com/avatar/82543e39dcc532109d25e5d2ea5838f3?s=80&d=https%3A%2F%2Fwww.snipsquirrel.com%2Fmedia%2Fsocialconnect%2Fimages%2Favatar.jpg
            [type] => 
        )

)

I think the main concern is the AuthLevels:

 [_authLevels:protected] => Array
        (
            [0] => 1
            [1] => 1
            [2] => 2
            [3] => 7
        )

Of which, "7" is he key access level for us that we have created.

Do you have any thoughts on this?

Many thanks

Adam

**Comment by billtomczak** [comment]
Hi Adam;

Thanks for the feedback!

The Simple Renew system plugin should take care of updating the session user object with the access a successful user subscription provides. Please check that the system plugin is installed and enabled for the site.

**Comment by ActiveOrganisation** [comment]
We will check Bill. Thanks (as ever) for your speedy response... We have had the install in for a while. And we have the latest version installed (as far as I am aware). I am sure it used to work but it is definitely doing something funny. Night time here in the UK so I'll check the plugin etc tomorrow with the guys and get back to you.

**Comment by billtomczak** [comment]
I just tested on our own staging site and as I expected (and hoped!)  I did not have to logout/login to refresh user permissions. Let me know what you find on your site and I'll help out as best I can.

**Comment by ActiveOrganisation** [comment]
To be clear, the User Object is being update/changed by SimpleRenew on subscription.... but not with all the right info... See user object "print_r" above...  We will un-install and re-install the component. And see what happens. For what it's worth, we're on Joomla 3.4.1

**Comment by billtomczak** [comment]
Sorry for the misunderstanding, Adam. Well, that's just plain odd then. Is it possible this started happening after a Joomla upgrade?

**Comment by billtomczak** [comment]
Adam;

From a purely practical standpoint, is this causing any actual trouble for your users?

I have found a potential issue and am investigating further.

**Comment by billtomczak** [comment]
Adam;

Would you be comfortable trying a simple patch?

**Comment by ActiveOrganisation** [comment]
Hi Bill,

Thanks for the replies. Sorry for the delay in responding. Was out yesterday. To answer your questions.

It could well have happened after a Joomla update. But I can't be sure. 

It would cause issues to users as they can't access the navigation they need post successful subscription completion - unless they log out and back in again,

I am more than happy to try any patch you provide Bill. Trust you guys 100%. We always back up before hand so, if it breaks, it's no problem... just re-install with Akeeba.

Happy to do whatever's needed.

**Comment by billtomczak** [comment]
Great! If I understand the problem (never guaranteed), this should fix the issue:

You'll find the code below here:
https://github.com/OSTraining/Simplerenew/blob/master/src/admin/library/simplerenew/Cms/Joomla/User/UserAdapter.php#L239

```php
        // If current user, refresh the session data
        if ($user->id == SimplerenewFactory::getUser()->id) {
            $session = SimplerenewFactory::getSession();
            $session->set('user', $user);
            SimplerenewFactory::getUser();
        }
```

Add one line of code after the if statement so it looks like this:
```php
        // If current user, refresh the session data
        if ($user->id == SimplerenewFactory::getUser()->id) {
            $user = new JUser($user->id);
            $session = SimplerenewFactory::getSession();
            $session->set('user', $user);
            SimplerenewFactory::getUser();
        }
```
If this does the trick, I will include it in the next release.

Thank you!

**Comment by ActiveScottShaw** [comment]
Hi Bill,

Many thanks for your reply.

We have just implemented the code change as requested, but sadly the issue still persists and the the user still needs to log back out in order for it to get the correct stuff :(

**Comment by billtomczak** [comment]
okay, thanks. Back to the drawing board.....

**Comment by billtomczak** [comment]
Hey Adam;

I have been quite surprised to discover that despite our intent to incorporate a fix for this problem into Simple Renew, it apparently slipped through the cracks. Also surprised this is the first time anyone has noticed. You should see a new release of SR in the update screen soon.
