### ISSUE TITLE
Add "Edit" button in "Account profile"

### ISSUE THREAD

**Issue by gibiwatch** [OSTraining/Simplerenew#359]
Low priority suggestion / feature request: it'd be nice to have an (optional) "Edit" button in the "Account profile" view, so that I don't have to create two different menu items. 

If you think the feature is ok I will try to code it and send a PR myself.

**Comment by billtomczak** [comment]
Thanks @gibiwatch! That would be great. I'll keep an eye out for your PR

**Comment by gibiwatch** [comment]
https://github.com/OSTraining/Simplerenew/pull/360

**Comment by billtomczak** [comment]
Duplicate.

PR merged into the development and now incorporated into [v1.1.13](https://github.com/OSTraining/Simplerenew/releases/tag/v1.1.13)
