### ISSUE TITLE
"refreshUserSession" means losing any other session information

### ISSUE THREAD

**Issue by gibiwatch** [OSTraining/Simplerenew#365]
I was debugging an issue with a 2FA auth plugin, and I found out that Simple Renew by default refresh the session user object at each new request:

    protected function refreshUserSession()
    {
        $current = JFactory::getUser();
        if ($current->id > 0) {
            $user = new JUser($current->id);

            $session = JFactory::getSession();
            $session->set('user', $user);
        }
    }

While I understand that this is meant to refresh groups and ACL settings without having the user logout and login again, this also means that any other component cannot use the session user object anymore, as any additional property / status will be wiped out. In our case, the 2FA plugin keep requesting the authentication token.

IMHO it will be better to take the existing user object from session, add or replace the required properties (let's say groups and access levels) and reinsert the updated user object into the session. 

If you agree that this is a reasonable workaround, I will work on it and issue a PR.

If this is not the case, I'd suggest to make the "refreshSession" behaviour optional with a configuration parameter.

**Comment by billtomczak** [comment]
Nice catch! Thank you so much! Agree that SR is being too heavy handed with updating the session object. It would be great to see something less disruptive.

I would appreciate the PR being issued against the development branch :)

**Comment by billtomczak** [comment]
Resolved by https://github.com/OSTraining/Simplerenew/compare/3f3f7f379708d949300bfc5bffb85b69d65e8d32...8aae414108a62f175e436d293756e67d83320c19
