### ISSUE TITLE
Batch sync of local accounts

### ISSUE THREAD

**Issue by gibiwatch** [OSTraining/Simplerenew#379]
Hello,
shortly: is there any plan for a CLI / background task that sync all existing accounts?

# Details

We are currently using a different integration extension for Recurly but we're close to migrating to SimpleRenew and group-based ACL. We already have existing subscriptions and we cannot wait until all of them are renewed (some are yearly) to trigger the changes via SimpleRenew web hook.

So we're planning to write a CLI app to perform an "on-demand" batch sync of all accounts.

Before writing any code, and since we plan to write it as an "addon" to SimpleRenew anyway, I'd like to check if you already have plans / code / tips. Thank you.

**Comment by billtomczak** [comment]
Take a look at [admin/cli](https://github.com/OSTraining/Simplerenew/tree/master/src/admin/cli) - for a ready-made bootstrap file and example cli application demonstrating its use.

I can't think of much reason to make this as complicated as as whole application. bootstrap.php will automatically load all the Simple Renew and Recurly libraries you should need to do whatever you want.

These came out of our own need for a cli application to support SRSubscriptions, an addon we haven't made generally available yet.

**Comment by gibiwatch** [comment]
That is definitely a good start. I will use the boostrap file and add the batch processing, trying to figure out the SimpleRenew API :-) 

Thank you for the tip. If you don't mind leaving this open for a few days, I will update with my progress.

**Comment by gibiwatch** [comment]
I was able to write a simple CLI sync script. I will open a PR just so you can take a look at it, I expect it'll have to be reviewed and adapted before considering inclusion in the project. Thank you for your tips!
