### ISSUE TITLE
Expired subscription but user is not removed from group

### ISSUE THREAD

**Issue by gibiwatch** [OSTraining/Simplerenew#380]
Hello, I need help to debug a wrong behaviour from SimpleRenew. Thank you in advance.

I am logging all notifications from Recurly so I'm sure we got a **expired_subscription_notification** for a given account, but the account is still in the related group. 

We received many other notifications and all other accounts have been correctly assigned / removed to the groups.

Questions:
* what are the possible causes of this wrong behaviours?
* how can I go deeper to debug what's happening?

Thank you.

**Comment by billtomczak** [comment]
If the user in question is a super user and your notification process is not logged in as a super user while running, then SR won't be able to make any user group changes. This is the only case I  know of.

What does the _simplerenew_push_log table show for that account? There might be a clue in there.

**Comment by gibiwatch** [comment]
Thanks for the tip about `_simplerenew_push_log` table, I did not know about it and it turned out to be very helpful in discovering the truth. 

Bottom line, there's nothing wrong in the component for this specific issue. It is true that the account had a subscription expired, but just before that he opened another subscription with a different plan **assigned to same group**. So everything appears to be correct.

Thank you and sorry for bothering you on a non-issue.

**Comment by billtomczak** [comment]
no problem! Glad it turned out okay
