### ISSUE TITLE
Allow to select more than one user group per plan

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/Simplerenew#385]
![groups](https://cloud.githubusercontent.com/assets/4999794/11509280/da6dea94-9822-11e5-8cd9-2858027ba824.jpg)
This will improve the UX; you don't need to create or edit an access level and usergroups to group several usergroups. Very useful for bundles.

**Comment by billtomczak** [comment]
This would require extensive changes to the DB and seems like it would introduce too much complexity.

**Comment by htmgarcia** [comment]
Good point.
Thanks @billtomczak !
