### ISSUE TITLE
Inconsistent Default Payment Option upon Install

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/Simplerenew#388]
Upon the initial install, only "Credit Card" is selected for "Payment Options", but "Default Payment Option" is set to "Paypal".

This makes the tab unselected in the front-end when testing.

@billtomczak with your approval, I'll switch "Default Payment Option" to "Credit Card" for new installs since they'll most likely start out in test mode (and Paypal doesn't work in Test Mode).

**Comment by billtomczak** [comment]
lol - yes, that's a bit of an inconsistency, isn't it? Please do! Thank you!

**Comment by nicksavov** [comment]
Thanks Bill! It was a minor change so I committed directly to master.
