### ISSUE TITLE
V1.20  "Join" page has non working tabs/buttons

### ISSUE THREAD

**Issue by vickythomas** [OSTraining/Simplerenew#394]
I just updated to v1.20 SR.  I checked the page that allows users to join and pay, and both the "Already Have An Account" button and the "Credit Card" tab seem non-functional ... nothing happens when clicked.  Also, the error messages only show one at a time when I leave required fields blank, I know it used to show all messages when"Subscribe" button was clicked.
My internet connection today is very slow, but I don't think that is the issue...
Please check/ assist.  Thank you!   Vicky

**Comment by vickythomas** [comment]
https://dnc.dressagenaturally.net/subscribe-now  is page

**Comment by billtomczak** [comment]
It's working with no problem in Chrome for me. I suspect it's a browser caching issue. Please try clearing browser cache and let us know. Thank you!

**Comment by vickythomas** [comment]
OK, thanks.  Sorry for the false alarm. Yes, all is OK after cleaning cache ... or decent internet connection finally.  All OK here now.  Thank you!

**Comment by billtomczak** [comment]
no problem! Better a false alarm than not addressing a potentially serious issue right away! Thanks again @vickythomas.
