### ISSUE TITLE
Checkout page info from Recurly

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/Simplerenew#398]
Is it possible to remove "for 1 month" from this template?
![screen shot 2016-01-14 at 12 15 01 pm](https://cloud.githubusercontent.com/assets/3868028/12354217/663f2f80-bb62-11e5-96b6-d4efe3dc51cf.png)

**Comment by htmgarcia** [comment]
@billtomczak wrapping "1 Month" in a span with a unique class should be enough. I would add a display: none; for that element then.

**Comment by OSTraining** [comment]
@htmgarcia - sounds good to me. Feel free to make changes as you see fit.

**Comment by htmgarcia** [comment]
Nevermind. Language overrides did the trick: https://www.ostraining.com/welcome-support-yearly/

@stevejburge do you want me to apply the same for plans with longer periods than a month? 
https://www.ostraining.com/welcome-support-yearly/

**Comment by stevejburge** [comment]
@htmgarcia Yes, please

**Comment by OSTraining** [comment]
nice! Cool solution!

**Comment by htmgarcia** [comment]
Done. From now, we need to be sure all the new plans (such as deals) include the lenght in the name.
