### ISSUE TITLE
Analytics e-commerce integration

### ISSUE THREAD

**Issue by pvullioud** [OSTraining/Simplerenew#399]
What is the best way to integrate Google analytics e-commerce?
https://developers.google.com/analytics/devguides/collection/analyticsjs/ecommerce

Could be great to have an option or a plugin for that.

Thanks :)

**Comment by pvullioud** [comment]
we choose to create a system redirection plugin to "thank you" page. So it easy to track

**Comment by billtomczak** [comment]
That sounds like a great solution @pvullioud!
