### ISSUE TITLE
Convert to uppercase (?)

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/Simplerenew#400]
https://github.com/OSTraining/Simplerenew/blob/master/src/admin/library/html/plan.php#L46

From:

`$text .= ' ' . JText::plural('COM_SIMPLERENEW_PLAN_' . $client . '_LENGTH_' . $unit, $length);`

...into:

`$text .= ' ' . JText::plural('COM_SIMPLERENEW_PLAN_' . strtoupper($client) . '_LENGTH_' . strtoupper($unit), $length);`

**Comment by htmgarcia** [comment]
The output would be from:

`COM_SIMPLERENEW_PLAN_site_LENGTH_months`

...into:

`COM_SIMPLERENEW_PLAN_SITE_LENGTH_MONTHS`

**Comment by OSTraining** [comment]
The language code in Joomla takes care of normalizing string case (as it should).

See: https://github.com/joomla/joomla-cms/blob/3.4.x/libraries/joomla/language/language.php#L327

**Comment by htmgarcia** [comment]
Thanks for the clarification! :)
