### ISSUE TITLE
Change password / billing confusion

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/Simplerenew#407]
A user had a very good point about this screen:
https://www.ostraining.com/account/updatebilling

They were intimidated and confused. They paid with PayPal. Why do they need to see credit card options to update their password?
![screen shot 2016-02-16 at 3 58 43 pm](https://cloud.githubusercontent.com/assets/3868028/13090912/88a18b68-d4c6-11e5-9db6-b2bc6386009c.png)

**Comment by billtomczak** [comment]
If that screenshot had come from a user using PayPal account, there should have been a message mentioning that they are registered as such.

We could certainly hide the CC data fields for  PayPal users, but I would be reluctant to get rid of it entirely in cases where they might want to switch to a credit card.

**Comment by stevejburge** [comment]
Hey Bill

This guy paid with PayPal and swears he saw a credit card form

**Comment by billtomczak** [comment]
Yes - the credit card form is always shown. But he should have also seen a reference to his PayPal agreement via Recurly.

**Comment by stevejburge** [comment]
He did - check the image I posted.

But I can see how that's confusing.

**Comment by billtomczak** [comment]
Ahh... the image you posted doesn't show the paypal message:

![paypal](https://cloud.githubusercontent.com/assets/3068131/13091912/2d650112-d4b2-11e5-9842-3b8dc35d2b45.png)

**Comment by stevejburge** [comment]
I logged in as him and that's what I saw

**Comment by billtomczak** [comment]
okay - wasn't clear to  me based on the image you uploaded.

So okay - maybe a bit confusing. But, by removing the CC form entirely in this situation it will require an admin to manually enter their CC information if they want to switch. Maybe hide the form with a link/button to show it?

**Comment by stevejburge** [comment]
Could we split the forms? One screen to update account info and a second to update billing?

**Comment by billtomczak** [comment]
Seems like a pretty drastic change. I wonder how other users of SR would feel about that.

You could already do something like this by using the standard Joomla editing form for account only changes and use this form for the additional billing  updates.

**Comment by stevejburge** [comment]
Ah, OK. If we use this page just for billing, will they see all the username and password stuff?

**Comment by billtomczak** [comment]
Yes - no changes. 

We could create a menu option to  choose showing the billing info only. This would retain the existing behavior (no big surprises for existing SR users) but provide the sort of setup you're looking for.

**Comment by stevejburge** [comment]
Might be worth it? We're overloading this form with different tasks

**Comment by billtomczak** [comment]
meh. Considering this is the only report we've received in almost a year of operation, I'm not so convinced of that. But it isn't a big deal to make these changes and it's a perfectly reasonable concern.

**Comment by stevejburge** [comment]
Thanks Bill

**Comment by billtomczak** [comment]
New option created, have fun!

**Comment by htmgarcia** [comment]
I like how the message about paypal was working, btw.

**Comment by billtomczak** [comment]
I'm reopening this because I think doing what we just did might create some unintended consequences and possibly cause more confusion. I will review and adjust as needed.

**Comment by billtomczak** [comment]
Closing in deference to new issues #409 and #408 

We *did* break the form :)

**Comment by nicksavov** [comment]
btw, I removed the images since they contained names, email addresses, and billing agreement IDs. Not a huge issue, but better safe than sorry. Hope that's OK.

**Comment by billtomczak** [comment]
Thanks Nick!
