### ISSUE TITLE
Remove the 1. from the payment form

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/Simplerenew#408]
Just a small thing, but we can probably remove numbers from headings. For example ...
![screen shot 2016-02-17 at 12 31 52 pm](https://cloud.githubusercontent.com/assets/3868028/13118537/97e2b8de-d572-11e5-83c9-68cd021c5e23.png)

**Comment by htmgarcia** [comment]
Numbers are a visual way to state the required steps to sign up or upgrade a membership.

**Comment by stevejburge** [comment]
True, but not needed in some situations, like the one above

**Comment by htmgarcia** [comment]
@stevejburge how can I reach that page?

**Comment by htmgarcia** [comment]
Nevermind, I find it: https://www.ostraining.com/account/updatebilling/
