### ISSUE TITLE
PayPal express support (no redirect)

### ISSUE THREAD

**Issue by vdrover** [OSTraining/Simplerenew#410]
We recently switched to PayPal Pro for our payment processing. In recurly, this was dead-simple. 

Afterwards, i contacted my rep at PayPal to verify our PAyPal Pro rates, and received the email below.

So for the paypal button, could PayPal Express be used instead? Better user experience and cheaper rates it seems.

```
Did you have the Express Checkout turned on? The transactions I see going through the account have just the Standard button. When you have PRO enabled, the Express Checkout is the best way to keep your credit card rates low. If your web team needs assistance, our integration team in in the office 9-6pm CST.

See the demo link: https://www.youtube.com/watch?v=qnDLl1MtU3w

Thank you, please keep me updated as to when the coding is changed. If you need assistance, let me know and I will get our Integration Team to help.

https://developer.paypal.com/docs/classic/express-checkout/in-context/integration/

There is an added bit of code that will make the PayPal payment just popup instead of redirect
Express Checkout lets you accept PayPal payments directly on your website and keeps your buyers there after they pay. We host the Express Checkout button and logo images that you use on your website.
```

**Comment by billtomczak** [comment]
It may not be possible to do this through the API. See https://docs.recurly.com/payment-gateways/paypal-payments

> PayPal payments are only available with the Recurly Hosted Payment Pages and Recurly.js. Customers will not be able to checkout using PayPal payments when using the Recurly API.

But I will contact Recurly and if it is possible, see what would be required to make it happen.

**Comment by billtomczak** [comment]
After discussion with Recurly, I've confirmed that we can't support something like PayPal express via the API. This can only be done through Recurly Hosted Payment pages. So even if we were to create an integration with Recurly hosted pages, users would still end up having to leave your site.

**Comment by nicksavov** [comment]
Vic, it's worth putting in a formal feature request to Recurly. They've implemented some items that we've requested before and then contacted us when it was available.

**Comment by vdrover** [comment]
is there a specific link? what features did they add for you?

**Comment by nicksavov** [comment]
Just their regular support email or form:
https://support.recurly.com/

I don't remember everything (we've been with them several years now), but they changed the way they do single-use coupons for trials and also improved their coupon management.

**Comment by vdrover** [comment]
done.

**Comment by nicksavov** [comment]
Thanks Vic!
