### ISSUE TITLE
Support one-time transactions?

### ISSUE THREAD

**Issue by RCheesley** [OSTraining/Simplerenew#411]
Recurly's API allows for one-time transactions as well as regular subscriptions - https://dev.recurly.com/docs/create-transaction.

We have a use case where a user has a regular subscription and runs out of credits, but does not want to upgrade (or they are on the highest plan) - and they need more credits just for that specific month.

We wanted to achieve this using a one-time transaction, made available by a menu only accessible to users with specified plans.

The current UI doesn't seem to suggest when creating plans that a one-time transaction is supported.  I'm not sure how best to achieve this - with a separate section for one-time transactions or to have an option when creating a plan to say whether it's a recurring or one-time.

Ruth

**Comment by nicksavov** [comment]
Hi Ruth,

Good question! We'll look into this tomorrow (Wednesday) for you and let you know what the options are.

**Comment by RCheesley** [comment]
Great, thanks Nick.

**Comment by billtomczak** [comment]
Hi @RCheesley;

Nick and I discussed this. Nick suggested that maybe you only need to be able to set up a specific plan that defaults to non-recurring? Does this make sense?

**Comment by RCheesley** [comment]
Not really, everything in the SimpleRenew UI seems to refer to repeating plans. Couldn't see how it would be hooking into the one-time transaction part of the API?  You would need to set up a plan in Recurly and I don't think it's possible to do that for non-recurring, but feel free to point out if I'm wrong!

**Comment by billtomczak** [comment]
Right. Of course the main point of using a service like Recurly is to manage recurring (potentially at least) subscriptions. Any connection to a plan would obviously fall into that system. So it sounds like you want users to be able to pay you some amount of money separate from any subscription plan?

**Comment by RCheesley** [comment]
Yes, using Reculy's one time transaction API functionality, which doesn't
seem implemented in SimpleRenew :)

Hope that makes sense now!
On 9 Mar 2016 18:27, "Bill Tomczak" <notifications@github.com> wrote:

> Right. Of course the main point of using a service like Recurly is to
> manage recurring (potentially at least) subscriptions. Any connection to a
> plan would obviously fall into that system. So it sounds like you want
> users to be able to pay you some amount of money separate from any
> subscription plan?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OSTraining/Simplerenew/issues/411#issuecomment-194437303>
> .
>

-- 

Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.

**Comment by billtomczak** [comment]
yes, I think I'm clear on this now.

It's true there are some updates to the core at least would be required to implement single transactions. But the more interesting issue would be how best to enter these sorts of transactions.

My thought in the beginning was to be able to leverage an installation of SR as a payment gateway for other e-commerce extensions. For example Virtuemart, Hikashop, etc. This would of course require the appropriate payment plugin for the target app.

But - if we want to provide these sorts of transactions internally to SR, it's difficult to know what a general purpose form for this would look like. My initial thought is this would be a candidate for a custom add-on for a specific purpose like yours. Still requiring some updates in SR core of course.

A general purpose payment form in core would require some clarification.

**Comment by RCheesley** [comment]
The use case we have was explained in the first post I think - a customer
with an ongoing subscription who, for whatever reason needs to then make a
one-off payment for something.

That could be a range of reasons - buying an item they need, in our case
topping up a subscription, making a one-time purchase of some special
offer, etc.

I could also see it might allow the purchase of goods alongside a
subscription, which we've found very difficult to do in the past.

Ruth
ᐧ

*Ruth Cheesley*
*CEO & Co-Founder*

Virya Group Limited

P: +44 (0) 1473 852130
E: ruth.cheesley@viryagroup.com
M: +44 (0) 7920 404314

On 9 March 2016 at 21:55, Bill Tomczak <notifications@github.com> wrote:

> yes, I think I'm clear on this now.
>
> It's true there are some updates to the core at least would be required to
> implement single transactions. But the more interesting issue would be how
> best to enter these sorts of transactions.
>
> My thought in the beginning was to be able to leverage an installation of
> SR as a payment gateway for other e-commerce extensions. For example
> Virtuemart, Hikashop, etc. This would of course require the appropriate
> payment plugin for the target app.
>
> But - if we want to provide these sorts of transactions internally to SR,
> it's difficult to know what a general purpose form for this would look
> like. My initial thought is this would be a candidate for a custom add-on
> for a specific purpose like yours. Still requiring some updates in SR core
> of course.
>
> A general purpose payment form in core would require some clarification.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OSTraining/Simplerenew/issues/411#issuecomment-194527217>
> .
>

-- 

Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.

**Comment by billtomczak** [comment]
Right. Its the idea of 'topping off' a subscription that is causing my confusion. I don't see how  transactions would accomplish this. It would have no effect on the user's subscription, just be some isolated charge to their billing account. Maybe for that what you're really looking for is something like adjustments? https://dev.recurly.com/docs/adjustment-object

**Comment by RCheesley** [comment]
I wasn't implying that they would have any impact on the subscription.  I
gave the full use case in the first request:

We have a use case where a user has a regular subscription and runs out of
credits, but does not want to upgrade (or they are on the highest plan) -
and they need more credits just for that specific month.

We wanted to achieve this using a one-time transaction, made available by a
menu only accessible to users with specified plans.
We have written an integration of SimpleRenew with Akeeba Tickets System.
The one-time top up will simply add more credits for the user for that
month. Subscription will continue un-affected.

Ruth

*Ruth Cheesley*
*CEO & Co-Founder*

Virya Group Limited

P: +44 (0) 1473 852130
E: ruth.cheesley@viryagroup.com
M: +44 (0) 7920 404314

On 10 March 2016 at 17:51, Bill Tomczak <notifications@github.com> wrote:

> Right. Its the idea of 'topping off' a subscription that is causing my
> confusion. I don't see how transactions would accomplish this. It would
> have no effect on the user's subscription, just be some isolated charge to
> their billing account. Maybe for that what you're really looking for is
> something like adjustments? https://dev.recurly.com/docs/adjustment-object
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OSTraining/Simplerenew/issues/411#issuecomment-194975383>
> .
>

ᐧ

-- 

Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.

**Comment by nicksavov** [comment]
Hi Ruth,

Also, feel free to have your developer(s) submit pull requests toward the Simple Renew core for any code that you feel would be best in core.

Cheers,

**Comment by RCheesley** [comment]
Thanks Nick, we thought that it would be the case that it wouldn't be on
the horizon but wanted to post it up anyways as a feature that could be
handy.  We will develop it in-house.

Ruth
ᐧ

*Ruth Cheesley*
*CEO & Co-Founder*

Virya Group Limited

P: +44 (0) 1473 852130
E: ruth.cheesley@viryagroup.com
M: +44 (0) 7920 404314

On 10 March 2016 at 22:29, Nick Savov <notifications@github.com> wrote:

> Hi Ruth,
>
> Also, feel free to have your developer(s) submit pull requests toward the
> Simple Renew core for any code that you feel would be best in core.
>
> Cheers,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OSTraining/Simplerenew/issues/411#issuecomment-195080114>
> .
>

-- 

Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.

**Comment by nicksavov** [comment]
Wonderful, glad to hear that, Ruth!

Cheers,

**Comment by billtomczak** [comment]
Thanks so much Ruth!
