### ISSUE TITLE
Welcome Message

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/Simplerenew#412]
hey @billtomczak 

Possible to remove this "Message" after joining?

![screen shot 2016-03-02 at 2 56 56 pm](https://cloud.githubusercontent.com/assets/3868028/13473395/37cbe162-e087-11e5-8e21-decdbb435165.png)

**Comment by htmgarcia** [comment]
In OST, we could just hide it with CSS. Not sure how easy could be.
 
In the other hand, I think is important to keep that message in SR core for UX purposes.

**Comment by stevejburge** [comment]
Sure thing, CSS works

**Comment by htmgarcia** [comment]
This is the page, right? https://www.ostraining.com/welcome/

**Comment by stevejburge** [comment]
Yep, that's it

**Comment by htmgarcia** [comment]
Added custom CSS code to hide the message in that article.
If anybody edit it in future, please disable the editor first.
