### ISSUE TITLE
Feature proposal: extend profile plugin

### ISSUE THREAD

**Issue by gibiwatch** [OSTraining/Simplerenew#413]
We wish to manage several user settings in one page, including billing info.

So I went to write a SimpleRenew profile plugin, only to find there is one already.

My idea is to extend the plugin to also **show** the settings as user profile data (i.e. implement `onContentPrepareForm` and such), possibly dependant from a component configuration setting.

Would you be interested in such an addition, or is it better for use to write a different plugin altogether?

**Comment by billtomczak** [comment]
CLosing in favor of #414
