### ISSUE TITLE
Display the version 

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/Simplerenew#415]
To improve support experience, it would be good to display the SR version within the extension in: Component > Simple Renew

In that way, when we ask about that detail, they can find it easily.

**Comment by billtomczak** [comment]
We used to do that. @stevejburge  requested it be removed. Way back in the before times :)

**Comment by billtomczak** [comment]
Appears in v1.2.0

**Comment by htmgarcia** [comment]
Thanks @billtomczak !
