### ISSUE TITLE
Update Billing doesn't appear to work

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/Simplerenew#418]
https://www.ostraining.com/account/updatebilling/ doesn't appear to work.

**Comment by billtomczak** [comment]
I take it the template does not automatically load jQuery?

SR was set to load only in the back end. I changed the option to always load.

**Comment by billtomczak** [comment]
btw this likely means the subscription pages were having difficulties.

**Comment by htmgarcia** [comment]
I don't see errors about jQuery, but still that page doesn't work properly. Very odd!

**Comment by billtomczak** [comment]
The jquery errors went away when I told SR to load it. Maybe a caching issue on your end?

**Comment by billtomczak** [comment]
ping @nicksavov @htmgarcia any further info on this?

It looks like it works with SR loading jQuery. Without SR loading, jQuery loads, but after SR functions try to use it and causing errors

**Comment by htmgarcia** [comment]
Still broken for me. The form can be submitted with empty fields for credit card.

**Comment by billtomczak** [comment]
That is to be expected and has been the behavior all along.
