### ISSUE TITLE
Page scrolling automatically to "First Name" hides previous fields

### ISSUE THREAD

**Issue by gibiwatch** [OSTraining/Simplerenew#419]
When opening the *Checkout* page, page scrolls down to "First Name" of "Credit card" instead of "First Name" of "Account". Is that intended? Can it be disabled? On small screen, this hides the fields at the top.

Live sample: https://watchful.li/subscribe-professional.html?view=subscribe

**Comment by billtomczak** [comment]
Sorry - That commit introduces a bug - still working on it.

**Comment by billtomczak** [comment]
@gibiwatch Please see 1d04e78850fafd83428e7ffcbfb0e0793c0cd500. This time I'll wait til you let me know if this fixes the issue for you before closing it :)

**Comment by gibiwatch** [comment]
@billtomczak from a quick test, this looks good. 

* Page is NOT scrolling down, so it's not hiding the first input fields (which was the original issue here).
* CreditCard tab is correctly activated.

Thank you!

**Comment by billtomczak** [comment]
Great to hear! Thanks @gibiwatch
