### ISSUE TITLE
J2.5 sites - SR w/new whitelisted webhook IPs

### ISSUE THREAD

**Issue by vickythomas** [OSTraining/Simplerenew#420]
We need a Simple Renew update with new whitelisted webhook IP addresses for the J2.5 sites - if done, which file is it?  Thanks, Vicky Thomas

**Comment by billtomczak** [comment]
V2.0.1 was just published just an hour ago or so. Just apply the update

**Comment by vickythomas** [comment]
yes, but i also also seems from what I read that the V 2 series is for J3.5 only ... will it break my J2.5 SR install?

**Comment by billtomczak** [comment]
ah yes - sorry about that.

The IP addresses can be updated here: https://github.com/OSTraining/Simplerenew/blob/v1.1.22/src/plugin/simplerenew/recurly/library/simplerenew/Gateway/Recurly/NotifyImp.php#L21

**Comment by vickythomas** [comment]
I would like liked a little notification in advance that you guys were stopping support of J2.5.  I will update this file with the new IP addresses, thank you for showing me which file.  Vicky

**Comment by billtomczak** [comment]
@vickythomas - my apologies for the lack of notice. I've created a legacy branch in case any other serious issues like this come up in the future. Any pre-2.x versoin will be kept compatible with Joomla 2.5. These will have to be downloaded and installed manually.

The new version can be found here: https://github.com/OSTraining/Simplerenew/releases/download/v1.1.23/com_simplerenew_free_1.1.23.zip

**Comment by vickythomas** [comment]
Thank you, Bill. That is really helpful.  btw, I've put upgrading this one site w/SR on the top of the to do list

**Comment by vickythomas** [comment]
@billtomczak   I got another Recurly notification tonight and I will be on a plane tomorrow, so I added all the IP addresses they listed to my J2.5 site NotifyImp.php file; does this seem OK?
`protected $validIpAddresses = array(
        '64.74.141.0/24',
        '8.36.93.0/24',
        '50.18.192.88',
        '52.8.32.100',
        '52.9.209.233',
        '50.0.172.150',
        '52.203.102.94',
        '52.203.192.184'
    );`

This Email came tonight at 8:41pm, is a bit confusing as the 'new' IP addresses are the ones you added earlier this month.
Dear Customer,
If you whitelist Recurly Webhooks IP network addresses, your immediate attention is required.
Starting on Wednesday, May 25, 2016, Recurly is making improvements to our network to provide you with faster, more reliable service.
What is changing? We are adding three additional IPs to our pool of available IPs.
How can I be prepared? Please be sure to include the three new IPs listed below.
•50.18.192.88 (new)
•52.8.32.100 (new)
•52.9.209.233 (new)
•50.0.172.150
•52.203.102.94
•52.203.192.184
If you do not currently restrict access via whitelisting on your firewalls or routers, no action is required.
If you have any questions, please contact us at support@recurly.com.
Sincerely,
Recurly Support

**Comment by billtomczak** [comment]
Yes Vicky, that is all correct. We've released new versions today.
For Joomla 2.5: https://github.com/OSTraining/Simplerenew/releases/download/v1.1.24/com_simplerenew_free_1.1.24.zip

Joomla 3.x users should see the update appear in the update manager
