### ISSUE TITLE
Success message

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/Simplerenew#421]
Can we edit this message after people subscribe?
![screen shot 2016-06-03 at 10 41 33 am](https://cloud.githubusercontent.com/assets/3868028/15782344/e3d2ecd8-2977-11e6-8e4a-03a15d2548d9.png)

**Comment by htmgarcia** [comment]
@stevejburge create a language override for the constant:

> COM_SIMPLERENEW_SUBSCRIPTION_PLAN_ADDED

Customize the text keeping **%s**:

> You are now a %s subscriber

**Comment by stevejburge** [comment]
Thanks @htmgarcia
