### ISSUE TITLE
Language string improvement

### ISSUE THREAD

**Issue by gibiwatch** [OSTraining/Simplerenew#422]
This is on:

* Joomla 3.4.8
* SimpleRenew 1.1.21

response:
- - -
Error

Your user account has been created on this site, but there a problem with your billing information: Your transaction was declined. Please use a different card or contact your bank.
- - -

this response is the same whether the user is new (in which case the user account is created) or a returning user (in which case no account is created contrary to the message the user receives). 

Either use a more generic message, or check the account status and use two different message.

**Comment by gibiwatch** [comment]
I opened this on SimpleRenew repository https://github.com/OSTraining/Simplerenew/issues/422

**Comment by gibiwatch** [comment]
@billtomczak has this been taken into consideration?

**Comment by billtomczak** [comment]
@gibiwatch, no haven't looked into this a priority so far. Could you create a pull request with proposed changes?

**Comment by gibiwatch** [comment]
Closing in favour of #425
